<option value=1>Rector</option>
<option value=2>Auxiliar administrativo</option>
<option value=3>Coordinador/ra</option>
<option value=4>Profesional administrativo</option>
<option value=5>Director/ra</option>
<option value=6>Vicerrector</option>
<option value=7>Asistente</option>
<option value=8>Auxiliar de Postgrados</option>
<option value=9>Auxiliar de Pregrados</option>
<option value=10>Enfermera</option>
<option value=11>Lider</option>
<option value=12>Psicólogo/ga</option>
<option value=13>Auxiliar de Cartera</option>
<option value=14>Auxiliar contable</option>
<option value=15>Asistente de presupuesto</option>
<option value=16>Tesorera</option>
<option value=17>Recepcionista</option>
<option value=18>Decano/na</option>
<option value=19>Profesional de Apoyo</option>
<option value=20>Profesional</option>
<option value=21>Practicante</option>
<option value=22>Especialista</option>
<option value=23>Diseñador/ra</option>
<option value=24>Community manager</option>
<option value=25>Webmaster</option>
<option value=26>Administrador de Redes</option>
<option value=27>Jefe de Almacén</option>
<option value=28>Auxiliar de Archivo</option>
<option value=29>Secretaria general</option>