<option value=1>Portatil</option>
<option value=2>Videobean</option>
<option value=3>Mouse</option>
<option value=4>Teclado</option>
<option value=5>Impresora</option>
<option value=6>Scaner</option>
<option value=7>Lector</option>
<option value=8>Switch</option>
<option value=9>Disco duro</option>
<option value=10>Cargador de portatil</option>