<option value=1>Rectoria</option>
<option value=2>Admisiones y Registro Academico</option>
<option value=3>Centro de Idiomas</option>
<option value=4>Investigaciones e Innovación</option>
<option value=5>Vicerrectoría Académica</option>
<option value=6>Centro de Graduados</option>
<option value=7>Prácticas Académicas</option>
<option value=8>Oficina de Mercadeo</option>
<option value=9>Centro de Innovación Educativa</option>
<option value=10>Vicerrectoría de Proyecto de Vida</option>
<option value=11>Área de Bienestar Social</option>
<option value=12>Centro de Familia</option>
<option value=13>Área de Desarrollo Humano</option>
<option value=14>Programa de Acompañamiento Académico</option>
<option value=15>Área de Expresión Cultural</option>
<option value=16>Área de Recreación y Deporte</option>
<option value=17>Pastoral Universitaria</option>
<option value=18>Gestión Financiera</option>
<option value=19>Oficina de Internacionalización y Relaciones Interinstitucionales</option>
<option value=20>Biblioteca Cardenal Darío Castrillón Hoyos</option>
<option value=21>Centro de Atención Psicológica</option>
<option value=2>Dirección Administrativa y Financiera</option>
<option value=23>Coordinación de Comunicaciones</option>
<option value=24>Gestión del Talento Humano</option>
<option value=25>Planeación y Calidad</option>
<option value=26>Gestion Tecnologica</option>
<option value=27>Gestión del Campus</option>
<option value=28>Secretaría General</option>
<option value=29>Proyección Social</option>
<option value=30>Recepción</option>
<option value=31>Decanatura de Arquitectura y Diseño</option>
<option value=32>Arquitectura</option>
<option value=33>Diseño Industrial</option>
<option value=34>Posgrados de Arquitectura y Diseño</option>
<option value=35>Talleres de diseño</option>
<option value=36>Decanatura de Ciencias Humanas, Sociales y de la Educación</option>
<option value=37>Centro de Medios</option>
<option value=38>Psicología</option>
<option value=39>Comunicación Social - Periodismo</option>
<option value=40>Licenciatura en Educación Religiosa</option>
<option value=41>Departamento de Humanidades</option>
<option value=42>Decanatura de Ciencias Económicas y Administrativas</option>
<option value=43>Administración de Empresas</option>
<option value=44>Economía</option>
<option value=45>Negocios Internacionales</option>
<option value=46>Programas de Mercadeo</option>
<option value=47>Tecnología en Gestión de Empresas Agroindustriales</option>
<option value=48>Punto de Bolsa Laboratorio de Econometría y Finanzas</option>
<option value=49>Decanatura de Ciencias Básicas e Ingeniería</option>
<option value=50>Ingeniería Industrial</option>
<option value=51>Ingeniería de Sistemas y Telecomunicaciones</option>
<option value=52>Tecnología en Desarrollo de Software</option>
<option value=53>Departamento de Ciencias Básicas</option>
<option value=54>Posgrados de Ciencias Humanas, Sociales y de la Educación</option>
<option value=55>Posgrados de Ciencias Económicas y Administrativas</option>
<option value=56>Posgrados de Ciencias Básicas e Ingeniería</option>